# 数据过滤项目配置文件

# 默认环境（本地环境）
default_env: "local"

# 多环境数据库配置
environments:
  # 本地环境（默认）
  local:
    host: "127.0.0.1"
    port: 5432
    username: "postgres"
    password: "123666"
    database: "postgres"
    sslmode: "disable"
    timezone: "Asia/Shanghai"

  # 香港测试环境
  hk-test:
    host: "mpg-rds-aurora-ae.cluster-c34408aa43zx.ap-east-1.rds.amazonaws.com"
    port: 5432
    username: "devadmin"
    password: "*ztnEY8n12"
    database: "mpgdb"
    sslmode: "require"
    timezone: "Asia/Shanghai"

  # 巴西测试环境
  br-test:
    host: "mpg-db-test.cnwcy0eo4x3k.sa-east-1.rds.amazonaws.com"
    port: 5432
    username: "devadmin"
    password: "*ztnEY8n12"
    database: "mpgdb"
    sslmode: "require"
    timezone: "Asia/Shanghai"

  # 巴西正式环境
  br-prod:
    host: "mpg-db-cluster.cluster-cnwcy0eo4x3k.sa-east-1.rds.amazonaws.com"
    port: 5432
    username: "devadmin"
    password: "*ztnEY8n12"
    database: "mpgdb"
    sslmode: "require"
    timezone: "Asia/Shanghai"

  # 美国正式环境
  us-prod:
    host: "mpg-db-cluster.cluster-cvwq2uy263dd.us-east-1.rds.amazonaws.com"
    port: 5432
    username: "devadmin"
    password: "*ztnEY8n12"
    database: "mpgdb"
    sslmode: "require"
    timezone: "Asia/Shanghai"

  # 香港正式环境
  hk-prod:
    host: "mpgdb.cluster-c34408aa43zx.ap-east-1.rds.amazonaws.com"
    port: 5432
    username: "devadmin"
    password: "*ztnEY8n12"
    database: "mpgdb"
    sslmode: "require"
    timezone: "Asia/Shanghai"

# Game Configuration
game:
  id: 1601012
  isFb: true

# Table Configuration
tables:
  source_table_prefix: "GameResultData_" # 读取数据的表前缀
  output_table_prefix: "GameResults_" # 写入数据的表前缀
  data_num: 10000 #普通流程
  data_table_num: 10 #普通流程表的数量
  data_num_fb: 5000 #购买夺宝模式
  data_table_num_fb: 1 #购买夺宝的表数量

# Bet Configuration (投注配置)
bet:
  cs: 1 # 投注额基数 (coin size)
  ml: 1 # 投注倍数 (multiplier)
  bl: 20 # 投注线数 (bet lines)
  fb: 75 # 购买夺宝的倍数
  # 实际投注额 = cs * ml * bl

# Prize Ratios (小数形式)
prize_ratios:
  # 大奖比例
  big_prize: 0.003
  # 巨奖比例
  mega_prize: 0.0008
  # 超巨奖比例
  super_mega_prize: 0.00065

# Gameplay Ratios (比例)
gameplay_ratios:
  # 普通玩法比例
  normal_gameplay: 0.3335
  # 特殊玩法比例
  special_gameplay: 0.0032

# RTP Configuration (Return to Player)
rtp:
  # 普通玩法RTP
  normal_gameplay: 0.7489
  # 特殊玩法RTP
  special_gameplay: 0.2180

# Stage Ratios Configuration (阶段策略配置)
stage_ratios:
  # 第一阶段占比下限（不盈利中奖数据）
  stage1_min_ratio: 0.60
  # 第一阶段占比上限（不盈利中奖数据）
  stage1_max_ratio: 0.80
  # 第三阶段用大额不盈利数据补充的比例
  stage3_win_top_ratio: 0.90
  # 允许上偏差
  upper_deviation: 0.005

# Additional Settings
settings:
  # 日志级别
  log_level: "info"
  # 数据处理批次大小
  batch_size: 5000
  # 超时设置（秒）
  timeout: 30
